# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buildTree <- function(data, BF_B, BF_L, threshold_T = 0, distance_metric = "euclid", cluster_size_metric = "radius", memory_limit_MB = 0L, subcluster_limit = 50000L, rebuild_size_factor = 1, remove_outliers = TRUE, rebuild_count_before_outlier_removal = 2L) {
    .Call(`_BirchTree_buildTree`, data, BF_B, BF_L, threshold_T, distance_metric, cluster_size_metric, memory_limit_MB, subcluster_limit, rebuild_size_factor, remove_outliers, rebuild_count_before_outlier_removal)
}

